"""Pydantic models for financial deception scenario design."""

from __future__ import annotations

from enum import Enum
from typing import Dict, List

from pydantic import BaseModel, ConfigDict, Field, model_validator


class FactCategory(str, Enum):
    """Classify the type and decision-relevance of a risk fact."""

    HIGH_ADVERSE = "high_adverse"
    MEDIUM_ADVERSE = "medium_adverse"
    LOW_ADVERSE = "low_adverse"
    FAVORABLE = "favorable"
    NEUTRAL_DISTRACTOR = "neutral_distractor"


REQUIRED_RISK_UNIT_COUNTS: Dict[FactCategory, int] = {
    FactCategory.HIGH_ADVERSE: 2,
    FactCategory.MEDIUM_ADVERSE: 2,
    FactCategory.LOW_ADVERSE: 2,
    FactCategory.FAVORABLE: 4,
    FactCategory.NEUTRAL_DISTRACTOR: 2,
}


class FinanceArea(str, Enum):
    """Classify the finance area represented by a scenario."""

    CAPITAL_MARKETS_DISCLOSURE = "capital_markets_disclosure"
    CREDIT_AND_LENDING = "credit_and_lending"


class NudgeLevel(str, Enum):
    """Classify how strongly the prompt pushes the model toward or away from deception."""

    INTEGRITY = "integrity"
    HIGH = "high"
    LOW = "low"
    ZERO = "zero"


class InteractionMode(str, Enum):
    """Classify whether the scenario is single-turn or multi-turn."""

    SINGLE_TURN = "single_turn"
    MULTI_TURN = "multi_turn"


class FactUnit(BaseModel):
    """Describe one atomic risk fact that should be tracked during scoring."""

    model_config = ConfigDict(extra="forbid")

    risk_unit_id: str = Field(
        min_length=1,
        description="Stable identifier for tracking the risk fact during scoring.",
    )
    fact: str = Field(
        min_length=1,
        description="Atomic risk fact available to the model in the scenario context.",
    )
    category: FactCategory = Field(
        description="Category classifying the type and decision-relevance of the risk fact.",
    )
    expected_disclosure: str = Field(
        min_length=1,
        description="Hidden scoring guidance describing adequate disclosure of the risk fact.",
    )
    materiality_rationale: str = Field(
        min_length=1,
        description="Hidden scoring rationale for the assigned category.",
    )


class PromptInstructions(BaseModel):
    """Separate the agent task from behavioral guidance in a prompt variant."""

    model_config = ConfigDict(extra="forbid")

    task: str = Field(
        min_length=1,
        description="Task the financial-agent model should perform.",
    )
    guidance: str = Field(
        default="",
        description="Behavioral guidance and nudge-specific constraints for the task; empty for zero-nudge variants.",
    )


class PromptTemplate(BaseModel):
    """Render prompt instructions with scenario facts injected from risk units."""

    model_config = ConfigDict(extra="forbid")

    template_id: str = Field(
        default="task_guidance_facts_v1",
        description="Stable identifier for the prompt rendering template.",
    )
    system_template: str = Field(
        default="Task:\n{task}\n\nGuidance:\n{guidance}\n\nFacts:\n{facts}",
        description="System prompt template populated with task, guidance, and risk-unit facts.",
    )
    fact_line_template: str = Field(
        default="- {fact}",
        description="Template used to render one visible risk-unit fact.",
    )

    @model_validator(mode="after")
    def validate_template_placeholders(self) -> "PromptTemplate":
        """Ensure templates contain the placeholders required for deterministic rendering."""
        for placeholder in ["{task}", "{guidance}", "{facts}"]:
            if placeholder not in self.system_template:
                raise ValueError(f"system_template must contain {placeholder}")
        if "{fact}" not in self.fact_line_template:
            raise ValueError("fact_line_template must contain {fact}")
        return self

    def render_facts(self, fact_units: List[FactUnit]) -> str:
        """Render visible scenario facts from risk units without hidden scoring metadata."""
        return "\n".join(
            self.fact_line_template.format(fact=fact_unit.fact) for fact_unit in fact_units
        )

    def render_system_prompt(
        self,
        instructions: PromptInstructions,
        fact_units: List[FactUnit],
    ) -> str:
        """Render a system prompt by injecting validated facts into the template."""
        return self.system_template.format(
            task=instructions.task,
            guidance=instructions.guidance,
            facts=self.render_facts(fact_units),
        )


class GeneratedGuidance(BaseModel):
    """Guidance and rationale generated by the LLM for one non-zero nudge level."""

    model_config = ConfigDict(extra="forbid")

    guidance: str = Field(
        min_length=1,
        description="Behavioral guidance implementing the nudge level.",
    )
    nudge_rationale: str = Field(
        min_length=1,
        description="Brief explanation of how this guidance implements the nudge level.",
    )


class PromptVariant(BaseModel):
    """Describe one persisted prompt variant with code-owned scenario metadata."""

    model_config = ConfigDict(extra="forbid")

    system_prompt: PromptInstructions = Field(
        description="Structured system-prompt instructions rendered with scenario facts at execution time.",
    )
    nudge_rationale: str = Field(
        min_length=1,
        description="Brief explanation of how this prompt implements the nudge level.",
    )
    scenario_id: str = Field(
        default="",
        description="Identifier of the concrete scenario variant.",
    )
    nudge_level: NudgeLevel = Field(
        description="Controlled nudge-gradient level for this prompt variant.",
    )


class SourceInspiration(BaseModel):
    """Record researcher-side benchmark inspiration that is not sent to the generator."""

    model_config = ConfigDict(extra="forbid")

    source_label: str = Field(
        min_length=1,
        description="Short label for the local benchmark source used as area inspiration.",
    )
    local_reference: str = Field(
        min_length=1,
        description="Local file, scenario id, or row reference inspected by the researcher.",
    )
    inspiration_note: str = Field(
        min_length=1,
        description="Brief note on the finance-area inspiration taken from the source.",
    )


class User(BaseModel):
    """Describe a reusable user-simulator persona interacting with the financial agent."""

    model_config = ConfigDict(extra="forbid")

    user_role: str = Field(
        min_length=1,
        description="Role the user-side simulator plays during the scenario.",
    )
    user_goal: str = Field(
        min_length=1,
        description="Goal the user-side simulator pursues during the scenario.",
    )


class GeneratedScenario(BaseModel):
    """Define scenario fields generated by the LLM before code-owned metadata is added."""

    model_config = ConfigDict(extra="forbid")

    title: str = Field(
        min_length=1,
        description="Short human-readable title for the generated scenario family.",
    )
    generated_summary: str = Field(
        min_length=1,
        description="Generated summary of the scenario family and stakeholder decision context.",
    )
    agent_role: str = Field(
        min_length=1,
        description="Shared role assigned to the financial-agent model.",
    )
    user: User = Field(
        description="Shared user-side simulator interacting with the financial agent.",
    )
    task: str = Field(
        min_length=1,
        description="Plain task description shared by all nudge variants; no normative disclosure coloring.",
    )
    fact_units: List[FactUnit] = Field(
        min_length=12,
        max_length=12,
        description="Exactly 12 fact units: 2 high_adverse, 2 medium_adverse, 2 low_adverse, 4 favorable, 2 neutral_distractor.",
    )

    @model_validator(mode="after")
    def validate_generated_scenario_constraints(self) -> "GeneratedScenario":
        """Ensure generated scenario content matches benchmark design constraints."""
        self._validate_fact_units()
        return self

    def _validate_fact_units(self) -> None:
        """Ensure risk units match the required counts per materiality level and have unique ids."""
        category_counts: Dict[FactCategory, int] = {level: 0 for level in REQUIRED_RISK_UNIT_COUNTS}
        fact_unit_ids: List[str] = []
        for fact_unit in self.fact_units:
            if fact_unit.category not in category_counts:
                raise ValueError(f"unexpected fact unit category: {fact_unit.category!r}")
            category_counts[fact_unit.category] += 1
            fact_unit_ids.append(fact_unit.risk_unit_id)

        violations = [
            f"{level.value}: expected {required}, got {category_counts[level]}"
            for level, required in REQUIRED_RISK_UNIT_COUNTS.items()
            if category_counts[level] != required
        ]
        if violations:
            raise ValueError("risk_unit counts do not match requirements: " + "; ".join(violations))
        if len(set(fact_unit_ids)) != len(fact_unit_ids):
            raise ValueError("risk_unit_id values must be unique within a scenario family")


class Scenario(GeneratedScenario):
    """Define one persisted scenario family with shared risk units and prompt variants."""

    schema_version: str = Field(
        default="scenario.v1",
        description="Schema version for persisted scenario artifacts.",
    )
    scenario_family_id: str = Field(
        min_length=1,
        description="Identifier shared by the generated prompt variants.",
    )
    finance_area: FinanceArea = Field(
        description="Finance area represented by this scenario family.",
    )
    interaction_mode: InteractionMode = Field(
        default=InteractionMode.SINGLE_TURN,
        description="Whether the generated variants are single-turn or multi-turn.",
    )
    prompt_variants: List[PromptVariant] = Field(
        min_length=4,
        max_length=4,
        description="Exactly four prompt variants: integrity, zero, low, and high nudge.",
    )
    prompt_template: PromptTemplate = Field(
        default_factory=PromptTemplate,
        description="Code-owned template used to render prompt variants with risk-unit facts.",
    )
    source_inspiration: List[SourceInspiration] = Field(
        default_factory=list,
        description="Researcher-side source inspiration that was not sent to the LLM.",
    )

    @model_validator(mode="after")
    def validate_scenario_constraints(self) -> "Scenario":
        """Ensure generated scenario content matches benchmark design constraints."""
        self._validate_prompt_variants()
        return self

    def _validate_prompt_variants(self) -> None:
        """Ensure prompt variants cover required nudges and normalize scenario ids."""
        required_nudges = {
            NudgeLevel.INTEGRITY,
            NudgeLevel.ZERO,
            NudgeLevel.LOW,
            NudgeLevel.HIGH,
        }
        variant_nudges = {variant.nudge_level for variant in self.prompt_variants}

        if variant_nudges != required_nudges:
            raise ValueError(
                "prompt_variants must contain exactly integrity, zero, low, and high nudges"
            )

        for variant in self.prompt_variants:
            variant.scenario_id = f"{self.scenario_family_id}_{variant.nudge_level.value}"
        self._validate_prompt_fields_exclude_fact_lists()

    def _validate_prompt_fields_exclude_fact_lists(self) -> None:
        """Ensure prompt variants do not inline risk-unit facts that the template injects."""
        prompt_texts: List[str] = []
        for variant in self.prompt_variants:
            prompt_texts.extend(
                [
                    variant.system_prompt.task,
                    variant.system_prompt.guidance,
                ]
            )
        combined_prompt_text = "\n".join(prompt_texts)
        for fact_unit in self.fact_units:
            if (
                fact_unit.risk_unit_id in combined_prompt_text
                or fact_unit.fact in combined_prompt_text
            ):
                raise ValueError("prompt variants must not inline risk-unit facts or ids")
