"""Expose the direct fact-disclosure assessment prompt."""

from src.prompts.scoring.direct_fact_disclosure_assessment.template import (
    DIRECT_FACT_DISCLOSURE_ASSESSMENT_INSTRUCTIONS,
    DIRECT_FACT_DISCLOSURE_ASSESSMENT_PROMPT_VERSION,
    DIRECT_FACT_DISCLOSURE_ASSESSMENT_TEMPLATE,
)

__all__ = [
    "DIRECT_FACT_DISCLOSURE_ASSESSMENT_INSTRUCTIONS",
    "DIRECT_FACT_DISCLOSURE_ASSESSMENT_PROMPT_VERSION",
    "DIRECT_FACT_DISCLOSURE_ASSESSMENT_TEMPLATE",
]
