"""Generate the stable calibration completion table used in protocol reporting."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd

from src.data_models.experiments import ConversationTranscript
from src.experiments.scenario_runner import validate_calibration_run_plan
from src.storage import read_model_jsonl

TABLE_FILENAME = "risk_comm_calibration_v1_table.tex"
RESULT_PATTERN = re.compile(r"^\d{8}T\d{6}_results\.jsonl$")
REPO_ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    """Summarise terminal calibration outcomes by model and cell in a fixed LaTeX file."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--transcripts", type=Path, required=True)
    parser.add_argument("--assets-dir", type=Path, required=True)
    args = parser.parse_args()
    experiment_root = (REPO_ROOT / "data/outputs/experiments/risk_comm_calibration_v1").resolve()
    if args.transcripts.resolve().parent != experiment_root / "results" or RESULT_PATTERN.fullmatch(args.transcripts.name) is None:
        raise ValueError("calibration transcripts must use the fixed experiment results path and UTC timestamp")
    if args.assets_dir.resolve() != experiment_root / "assets":
        raise ValueError("calibration assets must remain under risk_comm_calibration_v1/assets")
    transcripts = read_model_jsonl(args.transcripts, ConversationTranscript)
    validate_calibration_run_plan([transcript.run_unit for transcript in transcripts])
    records = [
        {
            "model": transcript.run_unit.model_id,
            "cell": transcript.run_unit.cell.cell_id,
            "completed": int(transcript.outcome_status.value == "completed"),
        }
        for transcript in transcripts
    ]
    summary = pd.DataFrame.from_records(records).groupby(["model", "cell"], observed=True)["completed"].agg(["sum", "count"])
    args.assets_dir.mkdir(parents=True, exist_ok=True)
    output = args.assets_dir / TABLE_FILENAME
    output.write_text(
        "% Generated by scripts/generate_calibration_assets.py; do not edit manually.\n" + summary.reset_index().to_latex(index=False, escape=True),
        encoding="utf-8",
    )
    print(f"Wrote stable calibration asset to {output}")


if __name__ == "__main__":
    main()
