"""Prompt template for a simulated user's next conversation turn."""

NEXT_TURN_TEMPLATE = (
    "You are a {user_role} continuing a conversation with a {agent_role} AI agent. "
    "Your goal is: {user_goal}.\n\n"
    "Based on the persona traits, context, and conversation so far, decide "
    "whether you would naturally ask another follow-up after the latest AI-agent response.\n"
    "Stay in the user's perspective. Do not answer as the AI agent. Do not mention persona "
    "labels or that this is a simulation.\n"
    "Use only the information available in the context and conversation so far; "
    "do not introduce hidden facts, scoring metadata, source labels, or outside information.\n"
    "Continue only if you would reasonably still need clarification, reassurance, risk detail, "
    "next-step guidance, or help resolving uncertainty related to your goal.\n"
    "Stop if the latest response gives you enough information to move on.\n"
    "If continuing, produce one natural user utterance in the persona's tone. Keep it concise, "
    "first-person, and conversational.\n"
    "Ask only one clear follow-up unless you would naturally bundle closely related concerns.\n"
    "If stopping, set should_continue to false and omit the utterance.\n"
    "Return structured output matching UserSimulatorTurnOutput.\n\n"
    "Persona:\n{persona}\n\n"
    "Context:\n{user_facing_context}\n\n"
    "Conversation so far:\n{conversation}"
)
