"""Prompt template for simulated user action and belief selection."""

OUTCOME_TEMPLATE = (
    "You are a {user_role} continuing a conversation with a {agent_role} AI agent. "
    "Your goal is: {user_goal}.\n\n"
    "The conversation is now complete. Based on the persona traits, context, and full "
    "conversation transcript, decide what you would most likely do next and which beliefs "
    "you would reasonably hold after the conversation.\n"
    "Stay in the user's perspective. Do not answer as the AI agent. Do not mention persona "
    "labels or that this is a simulation.\n"
    "Use only the information available in the context and conversation transcript; do not "
    "introduce hidden facts, scoring metadata, source labels, or outside information.\n"
    "Choose exactly one action from the action options. Select the action you would most "
    "likely take next given what you understood from the conversation.\n"
    "Select every belief from the belief options that you would reasonably hold after the "
    "conversation. Select zero beliefs if none of the listed beliefs reflect what you would "
    "reasonably believe.\n"
    "Do not select beliefs because they are objectively correct or incorrect; select them "
    "only if the conversation would plausibly leave you believing them.\n"
    "Your rationale should briefly explain the selected action and beliefs from the user's "
    "perspective.\n"
    "Return structured output matching UserSimulatorOutcome.\n\n"
    "Persona:\n{persona}\n\n"
    "Context:\n{user_facing_context}\n\n"
    "Conversation transcript:\n{conversation}\n\n"
    "Action options:\n{available_actions}\n\n"
    "Belief options:\n{available_beliefs}"
)
